### ISSUE TITLE
Suggestion - List and StringList

### ISSUE THREAD

**Issue by jondot** [olebedev/config#8]
Hi,
Would you think a StringList is useful on its own besides List? from my uses, it is very common to have a list of strings in configuration rather than list of interface{}

I'd love to hear your opinion on it
Thanks!

**Comment by olebedev** [comment]
Hi @jondot!

I'm not sure that is good idea. If we add StringList method we should also add UStringList, IntList,UIntList and so on. Because we cannot leave API inconsistence. As a result API will become too complicated.

My suggestion is use own struct with embedded config instance. In you case for example:
```go
type Conf struct {
	*config.Config
}

func (c *Conf) StringList(path string) error {
	result := []string{}
	
	l, err := c.List(path)
	if err != nil {
		return err
	}
	
	for _, i := range l {
		if item, err := i.(string); err != nil {
			return err
		} else {
			result = append(result, item)
		}
	}
	
	return result, nil
}
```

**Comment by jondot** [comment]
You are probably right, your suggestion is what I ended up with before coming here and asking about this :)
In any case I've replaced spf13/viper with olebedev/config in jondot/armor - and the result is much simpler and dependable, thanks!

**Comment by olebedev** [comment]
:+1: Glad to hear that!
